name: "Terraform Infrastructure Change Management Pipeline with GitHub Actions"
 
on:  # on event
 push:
   branches:
   - main

env: 
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
jobs: # Jobs to run on which operating system 
 demo:
   name: "Terraform Infrastructure Change Management"
   runs-on: ubuntu-latest
   defaults:
     run: 
       working-directory: ex1
     
   steps: # Stages to achive a job
    
     - name: Checkout the repository to the runner
       uses: actions/checkout@v2
             
     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v2
       with:
         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    
     - name: Terraform init
       id: init
       run: terraform init
 
     - name: Terraform plan
       id: plan
       run: terraform plan
 
     - name: Terraform Apply
       run: terraform apply -auto-approve
